.devcontainer/devcontainer.json
.vscode/terminal.sh
wizer/plotting/plot_history.py

provide script to run commands whenver new vscode integrated terminal is opened

---

setup/requirements/dev-requirements.txt
setup/requirements/requirements.in

recompile dev requirements

---

wizer/templates/activity/activity.html
wizer/templates/lib/base.html
wizer/templates/lib/keymap.html
wizer/templates/lib/sidebar.html
wizer/templates/sport/add_sport.html
wizer/templates/sport/sport_form.html
wizer/tests/integration_tests/browser_tests/test_activity_page.py
wizer/tests/integration_tests/browser_tests/test_sport_page.py

BUG: Fix sidebar responsiveness

---

.gitignore
setup/requirements/requirements.in
setup/requirements/requirements.txt
wizer/activity_views.py
wizer/forms.py
wizer/templates/activity/activity.html
wizer/templates/activity/add_activity.html
wizer/templates/activity/edit_activity.html
wizer/templates/lib/base.html
wizer/templates/lib/navbar.html
wizer/templates/lib/sidebar.html
wizer/tests/integration_tests/browser_tests/test_activity_page.py
wizer/tests/integration_tests/browser_tests/test_dashboard_page.py
wizer/tests/integration_tests/conftest.py
workoutizer/settings.py

FRONTEND: Add datetime picker to add+edit activity page

---

.devcontainer/devcontainer.json
.flake8
wizer/file_helper/fit_parser.py
wizer/templates/map/activity_map.html
wizer/tests/integration_tests/browser_tests/conftest.py
wizer/tests/integration_tests/browser_tests/test_activity_page.py
wizer/tests/integration_tests/conftest.py

BUG: only save and view laps with coordinates

---

wizer/configuration.py
wizer/file_helper/fit_parser.py
wizer/tests/unit_tests/file_helper/test_fit_parser.py

thereby fix displaying of fastest sections on map

ENH: drop records with null only early on

---

wizer/best_sections/fastest.py
wizer/tests/unit_tests/best_sections/test_fastest.py
wizer/tests/unit_tests/file_helper/test_fit_parser.py

workaround for this bug https://github.com/fgebhart/sportgems/issues/20

ENH: workaround for faulty treatment of null values in sportgems

---

wizer/configuration.py
wizer/file_helper/fit_parser.py
wizer/file_helper/gpx_parser.py
wizer/file_helper/parser.py
wizer/file_importer.py
wizer/templates/activity/activity_data.html
wizer/tests/integration_tests/browser_tests/test_activity_page.py
wizer/tests/unit_tests/file_helper/test_fit_parser.py

and safe guard for missing attributes in template, fixes #95

BUG: add postprocessing step to parser to get avg values

---

CHANGELOG.md
wkz/templates/lib/500.html
wkz/templates/lib/help.html
wkz/tests/browser_tests/test_error_pages.py
wkz/tests/browser_tests/test_generic.py
wkz/views.py
workoutizer/urls.py

ENH: add dedicated custom 500 error page and do not redirect this error

---

CHANGELOG.md
wkz/file_importer.py
wkz/tests/db_tests/test_import_demo_activities.py

BUG: read checksums from db inside the for loop to prevent unique constraint error

---

CHANGELOG.md
wkz/templates/lib/settings.html
wkz/tests/browser_tests/test_settings_page.py

ENH: add hover info on path to trace dir on settings page

---

CHANGELOG.md
wkz/file_helper/fit_collector.py
wkz/templates/activity/activity_facts.html
workoutizer/settings.py

ENH: Change logging

---

CHANGELOG.md
wkz/tools/utils.py

ENH: adding retry to calc_md5

---

CHANGELOG.md
wkz/api.py
wkz/configuration.py
wkz/file_helper/fit_parser.py
wkz/file_importer.py
wkz/models.py
wkz/tests/db_tests/test_import_activities.py
wkz/tests/unit_tests/file_helper/test_fit_parser.py
wkz/tools/sse.py
wkz/tools/utils.py

ENH: catch fit parser error and improve sse messages

---

.devcontainer/devcontainer.json
.vscode/terminal.sh
CHANGELOG.md
Dockerfile

ENH: modify vscode remote container configuration to work with recent release

---

.devcontainer/devcontainer.json
.gitignore
Dockerfile
setup/requirements/dev-requirements.in
setup/requirements/dev-requirements.txt

- ~~[ ] tests added / passed~~
- ~~[ ] changelog entry~~

enable generating html reports using pytest

---

wkz/templates/settings/form.html
wkz/templates/settings/settings.html

- ~~[ ] tests added / passed~~
- ~~[] changelog entry~~

ENH: add headings and more textual info to settings page

---

wkz/tests/browser_tests/test_settings_page.py
wkz/tests/conftest.py
wkz/tests/db_tests/conftest.py
wkz/tests/db_tests/test_cli.py
wkz/tests/db_tests/test_import_activities.py
wkz/tests/db_tests/test_reimporting_activities.py
wkz/tests/db_tests/test_watchdogs.py

TST: use auto fixture to ensure only one settings record is available + tracks in tmpdir

---

pytest.ini
wkz/configuration.py
wkz/file_importer.py
wkz/models.py
wkz/tests/browser_tests/test_settings_page.py
wkz/tests/conftest.py
wkz/tests/db_tests/test_import_activities.py
wkz/tests/db_tests/test_watchdogs.py
workoutizer/cli.py

ENH: make importer more robust to properly handle integrity error

---

CHANGELOG.md
wkz/templates/lib/footer.html
wkz/tests/browser_tests/test_dashboard_page.py
wkz/tests/browser_tests/test_help_page.py
wkz/tests/browser_tests/test_settings_page.py

ENH: show love only on settings and help page

---

CHANGELOG.md
tests/db_tests/test_import_activities.py
tests/db_tests/test_reimporting_activities.py
tests/unit_tests/gis/test_geo.py
wkz/activity_views.py
wkz/best_sections/generic.py
wkz/configuration.py
wkz/gis/geo.py
wkz/plotting/plot_time_series.py
wkz/templates/map/activity_map.html

ENH: reduce data points for plotting to speed up activity page load

---

tests/unit_tests/file_helper/test_fit_collector.py
tests/unit_tests/tools/test_utils.py
wkz/file_helper/fit_collector.py
wkz/file_helper/parser.py
wkz/file_importer.py
wkz/tools/utils.py
wkz/watchdogs.py

CLN: cleanups and improved logging for file import

---

tests/db_tests/test_import_activities.py
tests/unit_tests/file_helper/test_fit_collector.py
wkz/file_helper/fit_collector.py

TST: add tests to verify collecting and importing of upper case file endings works

---

CHANGELOG.md
wkz/configuration.py
wkz/file_importer.py
wkz/tasks.py

BUG: close dask clusters to avoid memory leak

---

CHANGELOG.md
wkz/file_importer.py

BUG: reduce worker count to 1 to avoid timeout issues

---

wkz/demo.py

ENH: disable awards for swimming demo sport

---

CHANGELOG.md
wkz/file_importer.py
wkz/templates/lib/help.html

ENH: release worker memory after importing a file to reduce memory footprint

---

.devcontainer/devcontainer.json
.vscode/settings.json
tests/db_tests/test_reimporting_activities.py

TST: enhance reimport test to verify path gets updated

---

CONTRIBUTING.md
Readme.md
wkz/file_importer.py

DOC: add changelog, cleanup readme

---

CONTRIBUTING.md
wkz/demo.py

RFC: refactor demo sports to avoid hard-coding swimming attributes twice

---

CHANGELOG.md
tests/db_tests/test_api.py

TST: Mock output of new _find_device_type function

---

CHANGELOG.md
setup.py
tests/db_tests/browser_tests/test_help_page.py
tests/db_tests/test_cli.py
workoutizer/__init__.py
workoutizer/cli.py
workoutizer/settings.py

ENH: parse version from git tags and add `check-for-update` to cli

---

CHANGELOG.md
workoutizer/__init__.py

FIX: enable reading wkz version for aalready installed packages

---

setup.py
tests/db_tests/browser_tests/test_settings_page.py
wkz/watchdogs.py
workoutizer/cli.py

- ~[ ] Ensure pre-commit formatting checks are passing~

ENH: add license and update cli functions

---

setup/Readme.md

Update `setup/Readme.md` to reflect new support for block devices

DOC: Updated Readme to reflect support for block devices

---

CHANGELOG.md
wkz/file_helper/fit_collector.py

The If statement was always false, due to comapring the wrong values. 
Also stripping the newline from the `gio` mount to avoid substring for printing of message
This fixes #183

Fix mounting block devices (Fixes #183)

---

tests/db_tests/browser_tests/test_awards_page.py
tests/db_tests/browser_tests/test_dashboard_page.py
tests/db_tests/browser_tests/test_generic.py
tests/utils.py

TST: add more waits in order to fix flaky chrome tests

---

CHANGELOG.md
setup/requirements/requirements.in
setup/requirements/requirements.txt
tests/db_tests/test_import_activities.py
tests/unit_tests/best_sections/test_climb.py
tests/unit_tests/file_helper/test_fit_parser.py
wkz/file_helper/fit_parser.py
wkz/plotting/plot_time_series.py

FIX: bump fitparse and use enhanced_altitude instead of altitude

---

CHANGELOG.md
wkz/file_helper/fit_parser.py

ENH: read altitude field in case enhanced_altitude is unavailable

---

setup/Readme.md
wkz/api.py
wkz/static/js/plugins/moment.min.js

ENH: Improve RPI install instructions, bump moment.js version

---

CHANGELOG.md
wkz/plotting/plot_history.py
wkz/plotting/plot_time_series.py

ENH: render activity duration in hover tooltip in dashboard history plot

---

tests/db_tests/test_api.py
wkz/file_helper/fit_collector.py

FIX: fix mounted message and enhance test to cover it

---

tests/db_tests/browser_tests/conftest.py
tests/db_tests/browser_tests/test_activity_page.py

TST: add test for bokeh button rendering different lap lines

---

tests/db_tests/test_api.py
tests/db_tests/test_export_gpx_file.py
wkz/file_helper/fit_collector.py
wkz/file_helper/parser.py
wkz/models.py

FIX: improper path manipulation (#53)

---

.github/workflows/single_test.yml

CI: remove formatting workflow stage on single test

---

.github/workflows/matrix_test.yml
.github/workflows/raspberry_pi_test.yml
.github/workflows/single_test.yml
Readme.md

CI: run tests only on .py and requirement file changes

---

CHANGELOG.md
tests/db_tests/browser_tests/test_awards_page.py
wkz/gis/geo.py

Fix geo location naming

---

setup/requirements/dev-requirements.in
setup/requirements/dev-requirements.txt
setup/requirements/requirements.in
setup/requirements/requirements.txt

upgrade lxml and pillow to remedy CVEs

---

tests/db_tests/browser_tests/test_activity_page.py
tests/db_tests/browser_tests/test_awards_page.py
tests/db_tests/browser_tests/test_dashboard_page.py
tests/db_tests/browser_tests/test_generic.py
tests/db_tests/browser_tests/test_help_page.py
tests/db_tests/browser_tests/test_settings_page.py
tests/db_tests/browser_tests/test_sport_page.py

RFC: get rid of selenium deprecation warnings by using recent func

---

.github/workflows/release.yml
wkz/io/file_importer.py

Test releasing

---

CHANGELOG.md
Dockerfile
poetry.lock
pyproject.toml
tests/db_tests/browser_tests/conftest.py
tests/db_tests/browser_tests/test_activity_page.py
tests/db_tests/browser_tests/test_generic.py
tests/db_tests/browser_tests/test_settings_page.py

TST: Drop chrome browser tests

---

tests/db_tests/browser_tests/test_awards_page.py
tests/db_tests/browser_tests/test_dashboard_page.py
tests/db_tests/test_reimporting_activities.py
tests/unit_tests/best_sections/test_climb.py
wkz/awards_views.py
wkz/best_sections/climb.py
wkz/best_sections/fastest.py
wkz/configuration.py
wkz/io/parser.py
wkz/views.py

RFC: refactor configuration of best secions

---

setup/Readme.md

DOC: ensure systemd wkz service waits for network to be available

---

.github/workflows/release.yml

CI: enable automated releasing by removing --dry-run

---

LICENSE
pyproject.toml

FIX: fix python version given in pyproject.toml, bump license

---

.github/workflows/matrix_test.yml
.github/workflows/raspberry_pi_test.yml
poetry.lock
pyproject.toml

DEP: upgrade dependencies

---

CHANGELOG.md
poetry.lock
pyproject.toml
tests/db_tests/browser_tests/test_activity_page.py
tests/unit_tests/best_sections/test_climb.py
tests/unit_tests/best_sections/test_fastest.py
tests/unit_tests/gis/test_geo.py
tests/unit_tests/io/test_gpx_parser.py
wkz/gis/geo.py

FIX: use haversine instead custom formula to fix rounding error

---

pyproject.toml

FIX: avoid wrong jinja version being installed
